package com.feed_the_beast.ftbl.lib.guide;

import com.feed_the_beast.ftbl.api.guide.GuideFormat;
import com.feed_the_beast.ftbl.api.guide.GuideType;
import com.feed_the_beast.ftbl.api.guide.SpecialGuideButton;
import com.feed_the_beast.ftbl.lib.client.ImageProvider;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import net.minecraft.util.text.TextComponentString;
import net.minecraft.util.text.TextComponentTranslation;
import net.minecraftforge.fml.common.ModContainer;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

/**
 * @author LatvianModder
 */
public class GuideTitlePage extends GuidePage
{
    private final GuideType type;
    private final GuideFormat format;
    private final List<String> authors;
    private final List<String> guideAuthors;

    public GuideTitlePage(String id, GuideType t, Collection<String> _authors, Collection<String> _guideAuthors)
    {
        super(id);
        type = t;
        format = GuideFormat.JSON;
        authors = _authors.isEmpty() ? Collections.emptyList() : new ArrayList<>(_authors);
        guideAuthors = _guideAuthors.isEmpty() ? Collections.emptyList() : new ArrayList<>(_guideAuthors);
    }

    public GuideTitlePage(ModContainer mod)
    {
        this(mod.getModId(), GuideType.MOD, mod.getMetadata().authorList, Collections.singleton("Autogenerated"));

        if(!mod.getMetadata().description.isEmpty())
        {
            for(String s : mod.getMetadata().description.split("\n"))
            {
                println(s);
            }
        }

        setTitle(new TextComponentString(mod.getName()));
    }

    public GuideTitlePage(String id, JsonObject o)
    {
        super(id);
        setTitle(new TextComponentTranslation(id + ".guide"));

        if(o.has("icon"))
        {
            setIcon(ImageProvider.get(o.get("icon")));
        }
        else
        {
            setIcon(ImageProvider.get(id + ":textures/icon.png"));
        }
        if(o.has("button"))
        {
            addSpecialButton(new SpecialGuideButton(o.get("button").getAsJsonObject()));
        }

        type = o.has("type") ? GuideType.getFromString(o.get("type").getAsString()) : GuideType.OTHER;
        format = o.has("format") ? GuideFormat.getFromString(o.get("format").getAsString()) : GuideFormat.JSON;

        List<String> l = new ArrayList<>();

        for(JsonElement e : o.get("authors").getAsJsonArray())
        {
            l.add(e.getAsString());
        }

        authors = Collections.unmodifiableList(l);

        l = new ArrayList<>();

        if(o.has("guide_authors"))
        {
            for(JsonElement e : o.get("guide_authors").getAsJsonArray())
            {
                l.add(e.getAsString());
            }
        }

        guideAuthors = Collections.unmodifiableList(l);
    }

    public GuideType getType()
    {
        return type;
    }

    public GuideFormat getFormat()
    {
        return format;
    }

    public List<String> getAuthors()
    {
        return authors;
    }

    public List<String> getGuideAuthors()
    {
        return guideAuthors;
    }
}