package com.feed_the_beast.ftbl.lib.gui;

import com.feed_the_beast.ftbl.lib.internal.FTBLibFinals;
import com.feed_the_beast.ftbl.lib.util.LangKey;

public interface GuiLang
{
	LangKey DONE = LangKey.of("gui.done");
	LangKey CANCEL = LangKey.of("gui.cancel");
	LangKey BACK = LangKey.of("gui.back");
	LangKey UP = LangKey.of("gui.up");
	LangKey DOWN = LangKey.of("gui.down");
	LangKey YES = LangKey.of("gui.yes");
	LangKey NO = LangKey.of("gui.no");
	LangKey NONE = LangKey.of("gui.none");
	LangKey ALL = LangKey.of("gui.all");
	LangKey EDIT = LangKey.of("selectServer.edit");
	LangKey OPTIONS = LangKey.of("options.title");
	LangKey PREV_PAGE = LangKey.of("createWorld.customize.custom.prev");
	LangKey NEXT_PAGE = LangKey.of("createWorld.customize.custom.next");
	LangKey DEFAULTS = LangKey.of("createWorld.customize.custom.defaults");
	LangKey DELETE = LangKey.of("selectServer.delete");
	LangKey REFRESH = LangKey.of("selectServer.refresh");
	String LANG_ENABLED = "addServer.resourcePack.enabled";
	LangKey ENABLED = LangKey.of(LANG_ENABLED);
	LangKey DISABLED = LangKey.of("addServer.resourcePack.disabled");
	LangKey ON = LangKey.of("options.on");
	LangKey OFF = LangKey.of("options.off");
	LangKey ACCEPT = LangKey.of("gui.accept");
	LangKey ADD = LangKey.of("gui.add");
	LangKey ADDED = LangKey.of("gui.added");
	LangKey REMOVE = LangKey.of("gui.remove");
	LangKey REMOVED = LangKey.of("gui.removed");
	LangKey CLOSE = LangKey.of("gui.close");
	LangKey CLOSED = LangKey.of("gui.closed");
	LangKey SAVE = LangKey.of("gui.save");
	LangKey SAVED = LangKey.of("gui.saved");
	LangKey LOAD = LangKey.of("gui.load");
	LangKey LOADED = LangKey.of("gui.loaded");
	LangKey INFO = LangKey.of("gui.info");
	LangKey COLLAPSE_ALL = LangKey.of("gui.collapse_all");
	LangKey EXPAND_ALL = LangKey.of("gui.expand_all");
	LangKey DOWNLOAD = LangKey.of("gui.download");
	LangKey DOWNLOADED = LangKey.of("gui.downloaded");
	LangKey UPDATE = LangKey.of("gui.update");
	LangKey UPDATED = LangKey.of("gui.updated");
	LangKey ACTIVE = LangKey.of("gui.active");
	LangKey INACTIVE = LangKey.of("gui.inactive");
	LangKey OTHER = LangKey.of("gui.other");
	LangKey SERVER_FORCED = LangKey.of(FTBLibFinals.MOD_ID + ".label.server_forced");
	LangKey ONLINE = LangKey.of("gui.online");
	LangKey OFFLINE = LangKey.of("gui.offline");
	LangKey WHITELIST = LangKey.of("gui.whitelist");
	LangKey BLACKLIST = LangKey.of("gui.blacklist");
	LangKey COLOR = LangKey.of("gui.color");
	LangKey DOWNLOADING = LangKey.of("gui.downloading");
	LangKey INFINITE = LangKey.of("gui.infinite");
	LangKey WIDTH = LangKey.of("gui.width");
	LangKey HEIGHT = LangKey.of("gui.height");
	String LANG_GENERAL = FTBLibFinals.MOD_ID + ".config.general";
}